# Plugins directory (XDG)
PLUGINS_DIR="$XDG_DATA_HOME/tmux/plugins"

# Bind prefix key to backtick
unbind C-b
set -g prefix `
bind ` send-prefix

# Split panes using "|" and "-"
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Statusbar
set -g status-interval 1

set -g status-position bottom
set -g status-justify left 
set -g status-style 'fg=red'

set -g status-left ''
set -g status-left-length 10

set -g status-right-style 'fg=black bg=yellow'
set -g status-right-length 50

set -g @prefix_highlight_empty_prompt ' TMUX '
set -g @prefix_highlight_empty_attr 'fg=default,bg=green' 
set -g @prefix_highlight_prefix_prompt 'PREFIX' 

setw -g status-right "#{prefix_highlight}"

setw -g window-status-current-style 'fg=black bg=red'
setw -g window-status-current-format ' #I #W #F ' 

setw -g window-status-style 'fg=red bg=black'
setw -g window-status-format ' #I #[fg=white]#W #[fg=yellow]#F'

setw -g window-status-bell-style 'fg=yellow bg=red bold'

# Binds
bind r source-file "$XDG_CONFIG_HOME/tmux/tmux.conf"

# vim-like bindings to navigate panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Plugins
run-shell $PLUGINS_DIR/tmux-prefix-highlight/prefix_highlight.tmux
run-shell $PLUGINS_DIR/tmux-resurrect/resurrect.tmux

